## initproc runtime config
## mode: run | shell | run_then_shell
mode=run

## 12-bit testcase mask (bit0..bit11):
## bit0=basic, bit1=busybox, bit2=lua, bit3=libctest,
## bit4=iozone, bit5=unixbench, bit6=iperf, bit7=libcbench,
## bit8=lmbench, bit9=netperf, bit10=cyclictest, bit11=ltp
## examples:
##   0x001 => only basic
##   0x103 => basic + busybox + lmbench
##   0xFFF => all 12 groups
mask=0x4
